services:
  - type: web
    name: ppl-automate
    env: docker
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: main # optional (defaults to master)
    # dockerCommand: ./webdis.sh # optional (defaults to Dockerfile command)
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: N8N_HOST
        value: https://ppl-automate.onrender.com/
      - key: N8N_EDITOR_BASE_URL
        value: https://ppl-automate.onrender.com/
      - key: PORT
        value: 5678
      - key: N8N_ENCRYPTION_KEY
        value: zbkX90A3Y2HQZcVLUOdScLz4aw3noXCZ
      - key: VUE_APP_URL_BASE_API
        value: https://ppl-automate.onrender.com/
      - key: WEBHOOK_URL
        value: https://ppl-automate.onrender.com/
      - key: TUNNEL_WEBHOOK_URL
        value: https://ppl-automate.onrender.com/
      - key: GENERIC_TIMEZONE
        value: America/Los_Angeles
      - key: TZ
        value: America/Los_Angeles
      - key: N8N_LOG_LEVEL
        value: verbose
      - key: DB_TYPE
        value: postgresdb
      - key: EXECUTIONS_DATA_PRUNE
        value: true
      - key: EXECUTIONS_DATA_MAX_AGE
        value: 72
      - key: EXECUTIONS_DATA_SAVE_ON_ERROR
        value: all
      - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
        value: none
      - key: EXECUTIONS_DATA_SAVE_ON_PROGRESS
        value: false
      - key: EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS
        value: false
      - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8nDB
          property: host
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8nDB
          property: database
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8nDB
          property: port
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8nDB
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8nDB
          property: password
      - key: PGHOST
        fromDatabase:
          name: n8nDB
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: n8nDB
          property: database
      - key: PGPORT
        fromDatabase:
          name: n8nDB
          property: port
      - key: PGUSER
        fromDatabase:
          name: n8nDB
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: n8nDB
          property: password
    disk:
      name: n8nDisk
      mountPath: /home/node/.n8n
      sizeGB: 1

databases:
  - name: n8nDB
    plan: starter
